En la primera parte de la clase 2 veremos algunos tipos de datos básicos de Python. **Esta Notebook no presenta una introducción exhaustiva, para eso recomendamos leer los tutoriales en el campus virtual de la materia.**

# **Números y strings**

En primer lugar, Python puede manejar enteros en distintas bases, números con coma flotante y números complejos.

In [4]:
a = 8         # Entero
b = 8.0       # Flotante
c = 1.4e80    # Científico
d = 0b100     # Binario
e = 43.2 + 3j # Complejo

Podemos verificar el tipo de datos usando type()

In [2]:
print(a, type(a))
print(b, type(b))
print(c, type(c))
print(d, type(d))
print(e, type(e))

8 <class 'int'>
8.0 <class 'float'>
1.4e+80 <class 'float'>
4 <class 'int'>
(43.2+3j) <class 'complex'>

Por supuesto, hay límites al tamaño de las variables que se pueden guardar en memoria.

En el caso de números con coma flotante, el número más grande posible (en módulo) es cercano a $1.8 \times 10^{308}$, mientras que el número con coma flotante positivo más pequelo es $5 \times 10^{-324}$.

Todo lo que está por arriba de $1.8 \times 10^{308}$ es infinito y todo lo que está por debajo de $5 \times 10^{-324}$ es 0.

In [5]:
print(1.8e308*10)
print(5e-324/10)

inf
0.0

Otro tipo de dato común son los strings (str).

In [6]:
a = "hola mundo"
b = 'mucho gusto'
print(type(a))
print(type(b))
print(a)
print(b)

<class 'str'>
<class 'str'>
hola mundo
mucho gusto

Los strings se pueden delimitar con comillas simples o dobles.
Esto es útil si quiero incluir comillas simples en el string (encierro con dobles) o si quiero incluir comillas dobles (encierro con simples)

In [ ]:
a = "Una comilla simple ' en mi string"
b = 'Una comilla doble " en mi string'
print(a)
print(b)

Pueden verificar que esto no funciona si encierro con el mismo tipo de comillas que usé dentro del string. Esto puede hacerse también usando \\' y \\" en lugar de ' y ". La barra delante de un caracter se denomina secuencia de escape y hace que ese caracter reciba un tratamiento especial.

Hay varios ejemplos, tales como \\n para una nueva linea, \\t para una tabulación, o \\\ si quiero que aparezca una sola barra invertida.

In [ ]:
print("hola\nmundo")
print("hola\tmundo")
print("hola\\mundo")

Puede que en alguna aplicación no nos interese el uso de la barra invertida para señalizar secuencias de escape. En ese caso podemos agregar una r (de raw, o crudo) delante del string para ignorar sistemáticamente todas ellas.

In [ ]:
print(r'hola\nmundo')

Tambiés es posible (y muy útil) encerrar strings en triple comillas de forma tal que se reproducen todas las barras invertidas y además no es necesario usar secuencia de escape para empezar nuevas lineas:

In [7]:
frase = """
hola
mundo
\que tal?
"""
print(frase)

hola
mundo
\que tal?

Una más de strings. En python 3.x hay f-strings, donde podemos llamar variables dentro de la string. Son una solución muy práctica al momento de armar strings de complejidad moderada, porque son fáciles de leer en el código.

In [8]:
nombre_autor  = 'Hermann Hesse'
nombre_novela = 'Siddhartha'
a_string = f'El es autor de la novela {nombre_novela} es {nombre_autor}'
print(a_string)

El es autor de la novela Siddhartha es Hermann Hesse

In [13]:
autor = {'Siddhartha':'Hermann Hesse', 
         'Los Hermanos Karamazov': 'Fedor Dostoivski', 
         '1Q84': 'Haruki Murakami', 
         'La Uruguaya': 'Pedro Mairal'}

for novela in autor:
  print(f'Es el escritor de la novela {novela} es {autor[novela]}')

print(type(autor))

Es el escritor de la novela Siddhartha es Hermann Hesse
Es el escritor de la novela Los Hermanos Karamazov es Fedor Dostoivski
Es el escritor de la novela 1Q84 es Haruki Murakami
Es el escritor de la novela La Uruguaya es Pedro Mairal
<class 'dict'>

Por último, hay un tipo de datos que se utiliza para codificar variables booleanas y tiene dos valores posibles True (verdadero) y False (falso). Podemos operar con estas variables usando operados booleanos como and y or

In [18]:
print(True or False)  # ¿Alguno es True?
print(True and False) # ¿Los dos son True?

True
False

El resultado de evaluar una proposición es una variable booleana

In [19]:
print(3==3)         # ¿3 es igual a 3?
print(3>2 or 2>3)   # ¿Alguna de estas dos condiciones es True?
print(2!=0 and 5<0) # ¿Es 2 diferente de 0, y además es 5 menor que 0?

True
True
False

# **Listas**

Las listas son una colección ordenada de elementos de distinto tipo, indexada desde 0 hasta n-1, donde n es la cantidad de elementos de la lista. La cantidad de elementos de la lista puede obtenerse usando la función len()

In [20]:
a = [1, 1.2, [3], True, 'hola', 3+3j]
print(len(a))
print(a[0])
print(a[len(a)-1])

6
1
(3+3j)

Notamos que las listas también pueden tener a otras listas como elementos (es el caso del elemento en la posición 2 de la lista de arriba).

Es posible seleccionar slices de listas usando una notación del estilo i:j, lo cual da una lista con los elementos desde la posición i a la j-1 (empezando desde 0).

In [21]:
print(a[2:5])

[[3], True, 'hola']

Hay otras formas más sofisticadas de hacer slices (por ejemplo, con números negativos) pero no lo necesitamos todavía. 

En Python, todo loop for se itera sobre una lista.

In [22]:
for item in a:
  print(item)

1
1.2
[3]
True
hola
(3+3j)

Si queremos iterar entre los números i, j-1 podemos usar la función range(), que genera una lista de enteros entre esos valores.

In [23]:
for n in range(4,10):
  print(n)

4
5
6
7
8
9

Hay muchas operaciones que podemos hacer con listas, como por ejemplo concatenarlas con el operador suma. Además, podemos trabajar con strings como si fuesen listas.

In [24]:
a = [1,2,3]
b = ['a', 'b', 'c']
print(a+b)
a = 'supercalifragilistico'
print(a[4:10])
print(a+ ' abracadabra')

[1, 2, 3, 'a', 'b', 'c']
rcalif
supercalifragilistico abracadabra

Una lista de Python es (como todo) un objeto y posee métodos. 
Los métodos son funciones específicas que solo se pueden aplicar a ese objeto. 
Tres ejemplos son revertir la lista con lista.reverse(), agregar un elemento o una lista al final con lista.append(), y remover un elemento de una posición determinada con lista.pop().

Es importante notar que aplicar los métodos no devuelven la lista modificada: únicamente la modifican en memoria, sin devolver nada. Por ejemplo:

In [25]:
a = [1, 1.2, [3], True, 'hola', 3+3j]
a.reverse()
print(a)

[(3+3j), 'hola', True, [3], 1.2, 1]

Pero si hago:

In [26]:
a = [1, 1.2, [3], True, 'hola', 3+3j]
print(a.reverse())

None

A pesar de que no devuelve nada, en la segunda linea del código aplicamos el método reverse, así que ahora la lista a está invertida:

In [27]:
print(a)

[(3+3j), 'hola', True, [3], 1.2, 1]

Las listas son un tipo de array. Hay 4 tipos de arrays

1.  Listas: Son colecciones ordenadas de elementos, son mutables (se puede modificar sus elementos), se encierran entre corchetes [ ]. 

2.  Tupples: Son colecciones ordenadas de elementos, son inmutables (no se puede modificar sus elementos), se encierran entre paréntesis ( ). 

3.  Sets: Son colecciones desordenadas de eleméntos únicos. Sirve para aplicar teoría de conjuntos.

4.  Diccionarios: Son colecciones ordenadas y mutables, sin valores duplicados.

In [39]:
miTupla = ('elemento 1', 'elemento 2', 'elemento 3', ['elemento 4'], 5, 6.0)
for i,n in enumerate(miTupla):
  print(f'El i = {i} de mi Tupla == {n}')

print(miTupla[2])

El i = 0 de mi Tupla == elemento 1
El i = 1 de mi Tupla == elemento 2
El i = 2 de mi Tupla == elemento 3
El i = 3 de mi Tupla == ['elemento 4']
El i = 4 de mi Tupla == 5
El i = 5 de mi Tupla == 6.0
elemento 3

# **Diccionarios**

El último tipo de dato natural a Python que vamos a repasar son los diccionarios.

Un diccionario consta de llaves, valores y un mapeo entre ambos que le asigna un valor a cada llave:

![dict.png]()

In [40]:
a = {'llave1':'hola', 'llave2':[True,False,3.5], 39:'hola mundo', 49.324:12}
print(a['llave1'])
print(a['llave2'])
print(a[39])
print(a[49.324])

hola
[True, False, 3.5]
hola mundo
12

Vemos que podemos usar el tipo de datos que queramos como llaves (aunque no listas) El problema surge cuando hay más de una llave con el mismo valor, porque en ese caso no sabemos a que valor hacemos referencia:

In [41]:
a = {'llave1':'hola', 'llave1':[True,False,3.5], 39:'hola mundo', 49.324:12}
print(a['llave1'])

[True, False, 3.5]

Vemos que obtenemos el último de los elementos con esa llave.
Si queremos saber cuales son todas las llaves de un diccionario podemos usar el método dict.keys()

In [62]:
llaves = a.keys()
print(llaves)

print('//////////////')

print(a.keys())
print(type(a.keys()))

dict_keys(['llave1', 39, 49.324])
//////////////
dict_keys(['llave1', 39, 49.324])
<class 'dict_keys'>

Que podemos convertir a una lista con la funcion list()

In [50]:
print(list(llaves))

['llave1', 39, 49.324]

## List comprehension
Python tiene una forma muy linda de definir listas, tupples y diccionarios

In [78]:
lista_pares    =  [number for number in range(10) if number%2==0]
tupple_impares =  (number for number in range(10) if number%2==1)
dict_pares     =  {number: number%2==0 for number in range(10)}
print(lista_pares)
print(tupple_impares)
print(dict_pares)

[0, 2, 4, 6, 8]
<generator object <genexpr> at 0x7f6d28059850>
{0: True, 1: False, 2: True, 3: False, 4: True, 5: False, 6: True, 7: False, 8: True, 9: False}

Los Generadores son objetos iterables, pero que no están cargados en memoria. Se ejecutan al momento de ser llamados, por lo que podemos correrlos en un for, pero no ocupan espacio en memoria.

In [79]:
for tup in tupple_impares:
  print(tup)
print('//////////////////////////')
for i in lista_pares:
  print(i)
print('//////////////////////////')
for i in dict_pares:
  print(i,dict_pares[i])

1
3
5
7
9
//////////////////////////
0
2
4
6
8
//////////////////////////
0 True
1 False
2 True
3 False
4 True
5 False
6 True
7 False
8 True
9 False

Los generadores tienen memoria sobre qué elemento ya llamé, y cuando los vuelvo a llamar pasan al siguiente. Cuando iteré sobre todos, ya no queda a quién llamar. Ojo con esto!

In [80]:
for tup in tupple_impares:
  print(tup)
print('//////////////////////////')
for i in lista_pares:
  print(i)
print('//////////////////////////')
for i in dict_pares:
  print(i,dict_pares[i])

//////////////////////////
0
2
4
6
8
//////////////////////////
0 True
1 False
2 True
3 False
4 True
5 False
6 True
7 False
8 True
9 False